baseURL = "https://lilkotyo.github.io/"
languageCode = "en-us"
title = "Ryao's Blog"
theme = "mini"
defaultContentLanguage = "zh"
showToc = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'